version: "3.5"
services:
   pegasus-donut:
      image: "${LOCAL_USER}/donut-remote-submission:pegasus-${PEGASUS_VERSION_NUM}"
      container_name: "pegasus-donut-${LOCAL_USER}"
      user: pegasus
      restart: always
      volumes:
         - ./data/.ssh:/home/pegasus/.ssh:rw
         - ./data/.bosco:/home/pegasus/.bosco:ro
         - ./data/.bashrc:/home/pegasus/.bashrc:ro
         - ./data/.pegasus:/home/pegasus/.pegasus:rw
         - ./data/config:/home/pegasus/config:ro
         - ./data/helpers:/home/pegasus/helpers:rw
         - ./data/workflows:/home/pegasus/workflows:rw
